ARG NODE_IMAGE=docker.io/library/node:20-alpine
FROM ${NODE_IMAGE}

ARG SHAPER_SOURCE_REVISION
LABEL org.opencontainers.image.title="SHAPER OS base packages"
LABEL org.opencontainers.image.revision="${SHAPER_SOURCE_REVISION}"

WORKDIR /shaper
COPY packages/ /shaper/packages/
